import maplibregl from "maplibre-gl";
import type { LngLatLike, MarkerOptions, PointLike } from "maplibre-gl";
import type { Map as SDKMap } from "../Map";
import type {
  MapTilerMarkerElementProps,
  MapTilerMarkerElementOptions,
  MapTilerMarkerSVGOptions,
  PendingMarkerUpdates,
  Vector2,
  MapTilerMarkerOptions,
  MarkerCollisionEventData,
} from "./types";
import { omit } from "../utils/object";
import { v4 as uuid } from "uuid";
import { applyMarkerStyleVariables, createMarkerElement, updateMarkerElement } from "./marker-dom-utils";
import { DEFAULT_SHAPE, DEFAULT_SIZE, SHAPES, SIZE_PX, getShapeAnchorOffset } from "./marker-svg-config";
import { getAdaptiveBgColor, resolveAdaptiveColor } from "./marker-adaptive-colors";
import { MarkerManager } from "./MarkerManager";
import type { MarkerFootprint } from "./collision-helpers";
import {
  PendingUpdatesSymbol,
  DetachFromDOMSymbol,
  FlushDOMUpdatesSymbol,
  MarkerElementSymbol,
  RefreshAdaptiveColorSymbol,
  CollisionFootprintSymbol,
  EmitCollisionDiffSymbol,
  ShouldHideSymbol,
  MeasuredElementSizeSymbol,
} from "./marker-symbols";

const maplibreMarkerConstructorOverrides: MarkerOptions = {
  scale: 1, // scale in our class will be a 2D vector.
};

const maptilerBaseOptionsKeys = [
  "shape",
  "size",
  "color",
  "innerColor",
  "outerColor",
  "contentColor",
  "outline",
  "outlineColor",
  "shadow",
  "opacity",
  "opacityWhenCovered",
  "name",
  "title",
  "content",
  "htmlAttributes",
  "scale",
  "visible",
  "priority",
  "userData",
  "collisionBehaviour",
  "collisionRadius",
  "rotation",
  "debug",
] as const;

/**
 * A MapTiler marker with extended styling and batched DOM update support.
 *
 * Extends MapLibre's `Marker` with 2-D scale, named shapes, colour tokens,
 * and a batched-update system that defers all DOM writes to the next animation
 * frame so that multiple property changes in the same tick cost only one
 * layout pass.
 */
export class Marker extends maplibregl.Marker {
  /**
   * The options used to construct this marker.
   * A construction-time snapshot — not updated by setters; use the getters
   * for current values.
   */
  readonly options: MapTilerMarkerOptions;
  readonly _scale = 1; // ML only allows scaling in 1 dimension, we want to add scaling in 2D so this is ignored.

  //#region Marker Properties

  /** Current values of all element-affecting properties. Written only via {@link setProp}. */
  private readonly props: MapTilerMarkerElementProps;

  /**
   * Whether the shape anchor offset is managed automatically.
   * `false` when the user supplied an explicit `offset` or a custom `element`.
   */
  private readonly managesOffset: boolean;

  /** The DOM element **/
  [MarkerElementSymbol]: HTMLElement;

  /** Property updates waiting to be flushed to the DOM on the next animation frame. */
  [PendingUpdatesSymbol]: PendingMarkerUpdates = {};

  /**
   * Unscaled CSS pixel size of a custom `element`, measured once by
   * {@link MarkerManager} when the marker is registered (the only time DOM
   * measurement is allowed — never during a collision pass).
   * `null` until measured; built-in SVG markers never need it.
   */
  [MeasuredElementSizeSymbol]: Vector2 | null = null;

  /** UUID that uniquely identifies this marker instance. */
  public readonly id = uuid();

  //#endregion

  //#region Constructor

  /**
   * Creates a marker whose content is a pre-built DOM or SVG element.
   *
   * SVG-layout fields (`shape`, `size`) are not available in this signature —
   * they only affect the built-in SVG generator.  Color and shadow options
   * are still accepted and applied as CSS custom properties on the supplied
   * element so that its styles can consume them.
   *
   * TODO: this will affect collision behaviour.
   */
  constructor(options: MapTilerMarkerElementOptions);
  /**
   * Creates a marker whose content is generated by the built-in SVG system.
   *
   * Use `shape`, `size`, colour tokens, and shadow to style the marker.
   */
  constructor(options: MapTilerMarkerSVGOptions);
  constructor(options: MapTilerMarkerOptions) {
    const sizeKey = options.size ?? DEFAULT_SIZE;
    const superOptions = {
      ...omit(options, maptilerBaseOptionsKeys),
      // custom-element markers get no automatic offset — their geometry is unknown
      offset: options.offset ?? (options.element ? undefined : getShapeAnchorOffset(options.shape ?? DEFAULT_SHAPE, sizeKey)),
    } as MarkerOptions;

    const element = options.element ?? createMarkerElement(options);

    super({
      element,
      ...superOptions,
      ...maplibreMarkerConstructorOverrides,
    });

    this[MarkerElementSymbol] = element;

    // custom elements skip createMarkerElement, so seed their style variables here
    if (options.element) applyMarkerStyleVariables(options.element, options);

    this.managesOffset = !options.offset && !options.element;

    this.props = {
      shape: options.shape,
      size: options.size,
      scale: Array.from(options.scale ?? [1, 1]) as Vector2,
      shadow: options.shadow,
      color: options.color,
      outerColor: options.outerColor,
      innerColor: options.innerColor,
      contentColor: options.contentColor,
      outlineColor: options.outlineColor,
      outline: options.outline,
      opacity: options.opacity,
      title: options.title,
      content: options.content,
      htmlAttributes: options.htmlAttributes,
      rotation: options.rotation,
      debug: options.debug,
      priority: options.priority,
    };

    if (typeof options.priority === "number") element.style.zIndex = String(options.priority);

    this.options = options;
  }

  //#endregion

  //#region Internal

  /**
   * Adds the marker to a map.
   *
   * Overrides the MapLibre signature to also accept the SDK `Map` type.
   * @param map - Target map instance.
   */
  addTo(map: SDKMap): this {
    return super.addTo(map);
  }

  /**
   * Recomputes the shape anchor offset on the parent MapLibre marker so the
   * shape's visual tip stays on the lngLat. No-op when the user supplied an
   * explicit `offset` or a custom `element`.
   */
  private applyShapeAnchorOffset(): void {
    if (!this.managesOffset) return;
    this.setOffset(getShapeAnchorOffset(this.props.shape ?? DEFAULT_SHAPE, this.props.size ?? DEFAULT_SIZE));
  }

  /**
   * Records a property's new value and schedules a DOM flush on the next
   * animation frame via {@link MarkerManager}.
   * @param prop - The element property to update.
   * @param value - The new value for the property.
   */
  private setProp<K extends keyof MapTilerMarkerElementProps>(prop: K, value: MapTilerMarkerElementProps[K]): void {
    this.props[prop] = value;
    this[PendingUpdatesSymbol][prop] = value;
    MarkerManager.addMarkerUpdateToQueue(this);
  }

  /**
   * Applies all pending property updates to the marker element and clears
   * the batch. Called by {@link MarkerManager} on the next animation frame.
   */
  [FlushDOMUpdatesSymbol](): void {
    const pending = this[PendingUpdatesSymbol];
    if (Object.keys(pending).length === 0) return;
    updateMarkerElement(this[MarkerElementSymbol], pending, this.getCurrentStyleId());
    this[PendingUpdatesSymbol] = {};
  }

  /** Returns the style id of the map this marker is on, or `undefined` when detached. */
  private getCurrentStyleId(): string | undefined {
    const map = MarkerManager.getMap(this);
    return map ? MarkerManager.getMapStyleId(map) : undefined;
  }

  /**
   * Queues a re-resolution of the adaptive `color` against the current map
   * style. Called by {@link MarkerManager} when the marker is registered and
   * whenever the map style changes. No-op when the marker has no adaptive
   * colour, or when an explicit `innerColor` pins the colour.
   */
  [RefreshAdaptiveColorSymbol](): void {
    if (this.props.color === undefined || this.props.innerColor !== undefined) return;
    this.setProp("color", this.props.color);
  }

  //#endregion

  //#region Collision

  /**
   * Resolves the marker's screen footprint for collision detection.
   *
   * Built entirely from stored props / lookup tables — no DOM reads — so it
   * is safe to call once per marker per detection pass. Called by
   * {@link MarkerManager} which pairs it with the marker's projected screen
   * position to build the collision box.
   */
  [CollisionFootprintSymbol](): MarkerFootprint {
    const [sx, sy] = this.props.scale ?? [1, 1];
    const offset = this.getOffset();
    const shared = {
      offset: [offset.x, offset.y] as Vector2,
      rotation: this.props.rotation ?? 0,
      mapAligned: this.getRotationAlignment() === "map",
    };

    // explicit collision radius replaces the visual box with a centred square
    const radius = this.options.collisionRadius;
    if (radius && radius > 0) {
      return { width: radius * 2, height: radius * 2, anchor: "center", ...shared };
    }

    const anchor = this.options.anchor ?? "center";

    // custom element: size measured once at registration
    if (this.options.element) {
      const [w, h] = this[MeasuredElementSizeSymbol] ?? [0, 0];
      return { width: w * sx, height: h * sy, anchor, ...shared };
    }

    // built-in SVG: height comes from the size key, width from the shape's
    // aspect ratio (see setMarkerSVGDimensions); `xs` renders a square dot
    const size = this.props.size ?? DEFAULT_SIZE;
    const heightPx = SIZE_PX[size];
    const shape = SHAPES[this.props.shape ?? DEFAULT_SHAPE];
    const widthPx = size === "xs" ? heightPx : heightPx * (shape.viewBox[0] / shape.viewBox[1]);
    return { width: widthPx * sx, height: heightPx * sy, anchor, ...shared };
  }

  /**
   * Fires the state-change collision event (`markeroverlap` or
   * `markerproximity`) for this marker. Called by {@link MarkerManager}
   * after diffing the pass results against the previous pass — only
   * transitions reach this point, unchanged collisions are never re-emitted.
   */
  [EmitCollisionDiffSymbol](data: MarkerCollisionEventData): void {
    this.fire(data.kind === "overlap" ? "markeroverlap" : "markerproximity", data);
  }

  /**
   * Whether the marker should currently be hidden by the collision engine.
   *
   * Placeholder seam for the behaviour layer: the next PR resolves this from
   * the marker's `collisionBehaviour` (see {@link CollisionBehaviour}),
   * `priority` and the detected collision groups. In this PR detection only
   * reports collisions — nothing is ever hidden.
   */
  [ShouldHideSymbol](): boolean {
    return false;
  }

  /**
   * Sets the marker's geographical position.
   *
   * Overridden to re-run collision detection — a marker moving changes
   * collisions with no map event to hang the pass on.
   * @param lnglat - The new position.
   */
  override setLngLat(lnglat: LngLatLike): this {
    super.setLngLat(lnglat);
    const map = MarkerManager.getMap(this);
    if (map) MarkerManager.invalidateCollisions(map);
    return this;
  }

  /**
   * Sets the marker's screen-space pixel offset.
   *
   * Overridden to re-run collision detection — the offset shifts the
   * marker's collision box.
   * @param offset - Offset in pixels (+y down).
   */
  override setOffset(offset: PointLike): this {
    super.setOffset(offset);
    const map = MarkerManager.getMap(this);
    if (map) MarkerManager.invalidateCollisions(map);
    return this;
  }

  //#endregion

  //#region Getters & Setters

  //#region Scale

  /**
   * Sets the 2-D scale of the marker as `[x, y]`.
   * @param scaleVector - Scale factors for the x and y axes.
   */
  setScale(scaleVector: Vector2) {
    this.setProp("scale", scaleVector);
  }

  /** Returns the current 2-D scale. Defaults to `[1, 1]`. */
  getScale() {
    return this.props.scale;
  }

  //#endregion

  //#region Shape

  /**
   * Sets the marker shape. Rebuilds the marker SVG in place, migrating the
   * current content (title / image / element) to the new shape's geometry.
   *
   * Has no visible effect on markers constructed with a custom `element`,
   * or while the size is `xs` (the dot rendering has no shape) — in the
   * latter case the shape is applied when the size next changes.
   * @param shape - Shape key (`rounded` | `circle` | `bubble-circle` | `bubble-square` | `square` | `bulb` | `squircle` | `shield`).
   */
  setShape(shape: MapTilerMarkerOptions["shape"]) {
    this.setProp("shape", shape);
    this.applyShapeAnchorOffset();
  }

  /** Returns the current shape, or `undefined` if never set. */
  getShape() {
    return this.props.shape;
  }

  //#endregion

  //#region Size

  /**
   * Sets the marker size.
   * @param size - T-shirt size key (`xs` | `s` | `m` | `l` | `xl`).
   */
  setSize(size: MapTilerMarkerOptions["size"]) {
    this.setProp("size", size);
    this.applyShapeAnchorOffset();
  }

  /** Returns the current size, or `undefined` if never explicitly set. */
  getSize() {
    return this.props.size;
  }

  //#endregion

  //#region Shadow

  /**
   * Sets the drop-shadow intensity.
   * @param shadow - Shadow preset (`soft` | `medium` | `strong`), or
   *   `undefined` to remove the shadow.
   */
  setShadow(shadow: MapTilerMarkerOptions["shadow"]) {
    this.setProp("shadow", shadow);
  }

  /** Returns the current shadow preset, or `undefined` if none is set. */
  getShadow() {
    return this.props.shadow;
  }

  //#endregion

  //#region Outer Color

  /**
   * Sets the fill colour of the outer body of the marker.
   * @param color - Any valid CSS colour string.
   */
  setOuterColor(color: MapTilerMarkerOptions["outerColor"]) {
    this.setProp("outerColor", color);
  }

  /** Returns the current outer body colour. */
  getOuterColor() {
    return this.props.outerColor;
  }

  //#endregion

  //#region Adaptive Color

  /**
   * Sets the adaptive colour of the marker. The inner (background) colour is
   * resolved against the current map style and re-resolved on style changes.
   * Clears any explicit `innerColor` so adaptation takes effect immediately.
   * @param color - Built-in palette name (`"blue"` | `"red"` | `"green"`), a
   *   custom `AdaptiveColor` definition, or `undefined` to remove.
   */
  setColor(color: MapTilerMarkerOptions["color"]) {
    this.props.innerColor = undefined;
    // an innerColor queued earlier in the same tick would override this batch
    delete this[PendingUpdatesSymbol].innerColor;
    this.setProp("color", color);
  }

  /** Returns the current adaptive colour (name or definition), or `undefined` if none is set. */
  getColor() {
    return this.props.color;
  }

  //#endregion

  //#region Inner Color

  /**
   * Sets an explicit fill colour for the inner area of the marker.
   * Takes precedence over the adaptive `color` and disables adaptation while
   * set; passing `undefined` re-enables the adaptive colour if one exists.
   * @param color - Any valid CSS colour string.
   */
  setInnerColor(color: MapTilerMarkerOptions["innerColor"]) {
    if (color === undefined && this.props.color !== undefined) {
      this.props.innerColor = undefined;
      this.setProp("color", this.props.color); // resume adaptation
      return;
    }
    this.setProp("innerColor", color);
  }

  /**
   * Returns the inner area colour currently in effect: the explicit
   * `innerColor` when set, otherwise the adaptive `color` resolved against
   * the current map style, otherwise `undefined` (default colour applies).
   */
  getInnerColor() {
    if (this.props.innerColor !== undefined) return this.props.innerColor;
    if (this.props.color !== undefined) {
      const adaptive = resolveAdaptiveColor(this.props.color);
      if (adaptive) return getAdaptiveBgColor(adaptive, this.getCurrentStyleId() ?? "");
    }
    return undefined;
  }

  //#endregion

  //#region Content Color

  /**
   * Sets the colour applied to the marker content (icon, text, etc.).
   * @param color - Any valid CSS colour string.
   */
  setContentColor(color: MapTilerMarkerOptions["contentColor"]) {
    this.setProp("contentColor", color);
  }

  /** Returns the current content colour. */
  getContentColor() {
    return this.props.contentColor;
  }

  //#endregion

  //#region Outline Color

  /**
   * Sets the stroke colour of the marker outline.
   * Has no visible effect unless {@link setOutline} is also called.
   * @param color - Any valid CSS colour string.
   */
  setOutlineColor(color: MapTilerMarkerOptions["outlineColor"]) {
    this.setProp("outlineColor", color);
  }

  /** Returns the current outline stroke colour. */
  getOutlineColor() {
    return this.props.outlineColor;
  }

  //#endregion

  //#region Outline

  /**
   * Sets the outline stroke width on the marker body.
   * @param outline - `true` for the default width, a positive `number` for an
   *   explicit pixel width, or `undefined` to remove the outline.
   */
  setOutline(outline: MapTilerMarkerOptions["outline"]) {
    this.setProp("outline", outline);
  }

  /** Returns the current outline value (`true`, a pixel width, or `undefined`). */
  getOutline() {
    return this.props.outline;
  }

  //#endregion

  //#region Title

  /**
   * Sets the `title` attribute on the marker's root element (native tooltip).
   * @param title - Tooltip string, or `undefined` to remove the attribute.
   */
  setTitle(title: MapTilerMarkerOptions["title"]) {
    this.setProp("title", title);
  }

  /** Returns the current title string. */
  getTitle() {
    return this.props.title;
  }

  //#endregion

  //#region Content

  /**
   * Sets the text content displayed inside the marker body.
   * @param content - Label string, or `undefined` to clear.
   */
  setContent(content: MapTilerMarkerOptions["content"]) {
    this.setProp("content", content);
  }

  /** Returns the current content string. */
  getContent() {
    return this.props.content;
  }

  //#endregion

  //#region Priority

  /**
   * Sets the rendering priority. Numeric values are applied as `z-index` on
   * the marker element, so higher-priority markers stack above lower ones.
   * Expression-form priorities are stored but only take effect once the
   * collision engine resolves them.
   * @param priority - Numeric priority, a MapLibre-style expression, or
   *   `undefined` to restore DOM-order stacking.
   */
  setPriority(priority: MapTilerMarkerOptions["priority"]) {
    this.setProp("priority", priority);
  }

  /** Returns the current rendering priority, or `undefined` if never set. */
  getPriority() {
    return this.props.priority;
  }

  //#endregion

  //#region Debug

  /**
   * Shows or hides the debug overlay, which renders the marker's bounding
   * box and center point on top of the marker element.
   * @param debug - `true` to show the overlay, `false`/`undefined` to hide it.
   */
  setDebug(debug: MapTilerMarkerOptions["debug"]) {
    this.setProp("debug", debug);
  }

  /** Returns whether the debug overlay is currently enabled. */
  getDebug() {
    return this.props.debug ?? false;
  }

  //#endregion

  //#region Rotation

  /**
   * Rotates the marker's inner shell element in degrees.
   *
   * Applied as part of the CSS `scale(x, y) rotate(deg)` compound transform
   * on the inner wrapper — independent of MapLibre's own rotation, which is
   * applied to the outer container element.
   * @param rotation - Clockwise rotation in degrees.
   */
  override setRotation(rotation: number): this {
    this.setProp("rotation", rotation);
    return this;
  }

  /**
   * Returns the current inner-shell rotation in degrees.
   * @returns Rotation in degrees; `0` if never set.
   */
  override getRotation(): number {
    return this.props.rotation ?? 0;
  }

  //#endregion

  //#endregion

  //#region Lifecycle

  /**
   * Removes the marker from the DOM directly, bypassing {@link MarkerManager}.
   *
   * Called by {@link MarkerManager.deregister} after it has already cleaned
   * up its own state — calling `remove()` here would cause infinite recursion.
   */
  [DetachFromDOMSymbol](): void {
    super.remove();
  }

  /**
   * Deregisters the marker from {@link MarkerManager} and removes it from
   * the map.
   * @returns `this` for chaining.
   */
  override remove(): this {
    if (MarkerManager.getMap(this)) {
      MarkerManager.deregister(this);
    } else {
      // never registered (added via addTo() directly) — plain MapLibre removal
      super.remove();
    }
    return this;
  }

  //#endregion
}
