import maplibregl from "maplibre-gl";
import type { MarkerOptions } from "maplibre-gl";
import type { Map as SDKMap } from "../Map";
import { HTMLElementUpdateCue, MapTilerMarkerElementProps, MapTilerMarkerElementOptions, MapTilerMarkerSVGOptions, Vector2, type MapTilerMarkerOptions } from "./types";
import { omit } from "../utils/object";
import { v4 as uuid } from "uuid";
import { createMarkerElement, updateMarkerElement, wrap } from "./marker-dom-utils";
import { DEFAULT_OFFSET_Y, DEFAULT_SIZE } from "./marker-svg-config";
import { MarkerManager } from "./MarkerManager";
import { CuedUpdatesSymbol, DetachFromDOMSymbol, FlushDOMUpdatesSymbol, MarkerElementSymbol } from "./marker-symbols";
export * from "./types";

const maplibreMarkerConstructorOverrides: MarkerOptions = {
  scale: 1, // scale in our class will be a 2D vector.
};

const maptilerBaseOptionsKeys = [
  "shape",
  "size",
  "innerColor",
  "outerColor",
  "contentColor",
  "outline",
  "outlineColor",
  "shadow",
  "opacity",
  "opacityWhenCovered",
  "name",
  "title",
  "htmlAttributes",
  "scale",
  "visible",
  "priority",
  "userData",
  "collisionBehaviour",
  "collisionRadius",
  "rotation",
] as const;

/**
 * A MapTiler marker with extended styling and batched DOM update support.
 *
 * Extends MapLibre's `Marker` with 2-D scale, named shapes, colour tokens,
 * and a cued-update system that defers all DOM writes to the next animation
 * frame so that multiple property changes in the same tick cost only one
 * layout pass.
 */
export class Marker extends maplibregl.Marker {
  /** The resolved options used to construct this marker. */
  options: MapTilerMarkerOptions;
  readonly _scale = 1; // ML only allows scaling in 1 dimension, we want to add scaling in 2D so this is ignored.

  //#region Marker Properties

  /** The size catetogry of the marker */
  private size: MapTilerMarkerOptions["size"];

  /** The scale vector of the marker [x, y] */
  private scaleVector: MapTilerMarkerOptions["scale"];

  /** The shadow option "soft" | "medium" | "strong" */
  private shadow: MapTilerMarkerOptions["shadow"];

  /** The color of the outermost part of the marker */
  private outerColor: MapTilerMarkerOptions["outerColor"];

  /** The color of the inner part of the marker */
  private innerColor: MapTilerMarkerOptions["innerColor"];

  /** The color of the inner part of the content */
  private contentColor: MapTilerMarkerOptions["contentColor"];

  /*& The color of the outline of the marker */
  private outlineColor: MapTilerMarkerOptions["outlineColor"];

  /** The width of the outline */
  private outline: MapTilerMarkerOptions["outline"];

  /** The value applied to the 'title' attribute of the marker */
  private title: MapTilerMarkerOptions["title"];

  /** The rotation of the marker in degrees */
  private markerRotation: number | undefined;

  /** The DOM element **/
  [MarkerElementSymbol]: HTMLElement;

  /** A Map used to store updates needed */
  [CuedUpdatesSymbol]: HTMLElementUpdateCue = new Map();

  /** UUID that uniquely identifies this marker instance. */
  public readonly id = uuid();

  //#endregion

  //#region Constructor

  /**
   * Creates a marker whose content is a pre-built DOM or SVG element.
   *
   * SVG-layout fields (`shape`, `size`) are not available in this signature —
   * they only affect the built-in SVG generator.  Color and shadow options
   * are still accepted and applied as CSS custom properties on the wrapper so
   * that the supplied element can inherit them.
   *
   * TODO: this will affect collision behaviour.
   */
  constructor(options: MapTilerMarkerElementOptions);
  /**
   * Creates a marker whose content is generated by the built-in SVG system.
   *
   * Use `shape`, `size`, colour tokens, and shadow to style the marker.
   */
  constructor(options: MapTilerMarkerSVGOptions);
  constructor(options: MapTilerMarkerOptions) {
    const sizeKey = options.size ?? DEFAULT_SIZE;
    const superOptions = {
      ...omit(options, maptilerBaseOptionsKeys),
      offset: options.offset ?? [0, DEFAULT_OFFSET_Y[sizeKey]],
    } as MarkerOptions;

    const element = options.element ?? createMarkerElement(options);

    super({
      element,
      ...superOptions,
      ...maplibreMarkerConstructorOverrides,
    });

    this[MarkerElementSymbol] = element;

    this.scaleVector = Array.from(options.scale ?? [1, 1]) as Vector2;
    this.outerColor = options.outerColor;
    this.innerColor = options.innerColor;
    this.contentColor = options.contentColor;
    this.outlineColor = options.outlineColor;
    this.outline = options.outline;
    this.title = options.title;
    this.markerRotation = options.rotation;

    this.options = options;
  }

  //#endregion

  //#region Internal

  /**
   * Adds the marker to a map.
   *
   * Overrides the MapLibre signature to also accept the SDK `Map` type.
   * @param map - Target map instance.
   */
  addTo(map: SDKMap): this {
    return super.addTo(map);
  }

  /**
   * Enqueues a single property update and schedules a DOM flush on the next
   * animation frame via {@link MarkerManager}.
   * @param prop - The element property to update.
   * @param value - The new value for the property.
   */
  private cueMarkerElementUpdate(prop: keyof MapTilerMarkerElementProps, value: MapTilerMarkerElementProps[keyof MapTilerMarkerElementProps]) {
    this[CuedUpdatesSymbol].set(prop, value);
    MarkerManager.addMarkerUpdateToQueue(this);
  }

  /**
   * Applies all cued property updates to the marker element and clears the
   * queue. Called by {@link MarkerManager} on the next animation frame.
   */
  [FlushDOMUpdatesSymbol](): void {
    if (this[CuedUpdatesSymbol].size === 0) return;
    updateMarkerElement(this[MarkerElementSymbol], this[CuedUpdatesSymbol]);
    this[CuedUpdatesSymbol].clear();
  }

  //#endregion

  //#region Getters & Setters

  /**
   * Sets the 2-D scale of the marker as `[x, y]`.
   * @param scaleVector - Scale factors for the x and y axes.
   */
  setScale(scaleVector: [number, number]) {
    this.cueMarkerElementUpdate("scale", scaleVector);
    this.scaleVector = scaleVector;
  }

  /** Returns the current 2-D scale, or `undefined` if never set. */
  getScale() {
    return this.scaleVector;
  }

  /**
   * Sets the marker size.
   * @param size - T-shirt size key (`xs` | `s` | `m` | `l` | `xl`).
   */
  setSize(size: MapTilerMarkerOptions["size"]) {
    this.cueMarkerElementUpdate("size", size);
    this.size = size;
  }

  /** Returns the current size, or `undefined` if never explicitly set. */
  getSize() {
    return this.size;
  }

  /**
   * Sets the drop-shadow intensity.
   * @param shadow - Shadow preset (`soft` | `medium` | `strong`), or
   *   `undefined` to remove the shadow.
   */
  setShadow(shadow: MapTilerMarkerOptions["shadow"]) {
    this.cueMarkerElementUpdate("shadow", shadow);
    this.shadow = shadow;
  }

  /** Returns the current shadow preset, or `undefined` if none is set. */
  getShadow() {
    return this.shadow;
  }

  /**
   * Sets the fill colour of the outer body of the marker.
   * @param color - Any valid CSS colour string.
   */
  setOuterColor(color: MapTilerMarkerOptions["outerColor"]) {
    this.cueMarkerElementUpdate("outerColor", color);
    this.outerColor = color;
  }

  /** Returns the current outer body colour. */
  getOuterColor() {
    return this.outerColor;
  }

  /**
   * Sets the fill colour of the inner area of the marker.
   * @param color - Any valid CSS colour string.
   */
  setInnerColor(color: MapTilerMarkerOptions["innerColor"]) {
    this.cueMarkerElementUpdate("innerColor", color);
    this.innerColor = color;
  }

  /** Returns the current inner area colour. */
  getInnerColor() {
    return this.innerColor;
  }

  /**
   * Sets the colour applied to the marker content (icon, text, etc.).
   * @param color - Any valid CSS colour string.
   */
  setContentColor(color: MapTilerMarkerOptions["contentColor"]) {
    this.cueMarkerElementUpdate("contentColor", color);
    this.contentColor = color;
  }

  /** Returns the current content colour. */
  getContentColor() {
    return this.contentColor;
  }

  /**
   * Sets the stroke colour of the marker outline.
   * Has no visible effect unless {@link setOutline} is also called.
   * @param color - Any valid CSS colour string.
   */
  setOutlineColor(color: MapTilerMarkerOptions["outlineColor"]) {
    this.cueMarkerElementUpdate("outlineColor", color);
    this.outlineColor = color;
  }

  /** Returns the current outline stroke colour. */
  getOutlineColor() {
    return this.outlineColor;
  }

  /**
   * Sets the outline stroke width on the marker body.
   * @param outline - `true` for the default width, a positive `number` for an
   *   explicit pixel width, or `undefined` to remove the outline.
   */
  setOutline(outline: MapTilerMarkerOptions["outline"]) {
    this.cueMarkerElementUpdate("outline", outline);
    this.outline = outline;
  }

  /** Returns the current outline value (`true`, a pixel width, or `undefined`). */
  getOutline() {
    return this.outline;
  }

  /**
   * Sets the text content displayed inside the marker.
   * @param title - Label string, or `undefined` to clear.
   */
  setTitle(title: MapTilerMarkerOptions["title"]) {
    this.cueMarkerElementUpdate("title", title);
    this.title = title;
  }

  /** Returns the current title string. */
  getTitle() {
    return this.title;
  }

  /**
   * Rotates the marker's inner shell element in degrees.
   *
   * Applied as part of the CSS `scale(x, y) rotate(deg)` compound transform
   * on the inner wrapper — independent of MapLibre's own rotation, which is
   * applied to the outer container element.
   * @param rotation - Clockwise rotation in degrees.
   */
  override setRotation(rotation: number): this {
    this.cueMarkerElementUpdate("rotation", rotation);
    this.markerRotation = rotation;
    return this;
  }

  /**
   * Returns the current inner-shell rotation in degrees.
   * @returns Rotation in degrees; `0` if never set.
   */
  override getRotation(): number {
    return this.markerRotation ?? 0;
  }

  //#endregion

  //#region Lifecycle

  /**
   * Removes the marker from the DOM directly, bypassing {@link MarkerManager}.
   *
   * Called by {@link MarkerManager.deregister} after it has already cleaned
   * up its own state — calling `remove()` here would cause infinite recursion.
   */
  [DetachFromDOMSymbol](): void {
    super.remove();
  }

  /**
   * Deregisters the marker from {@link MarkerManager} and removes it from
   * the map.
   * @returns `this` for chaining.
   */
  override remove(): this {
    MarkerManager.deregister(this);
    return this;
  }

  //#endregion
}
